### ISSUE TITLE
fix exception

### ISSUE THREAD

**Issue by carlosp420** [VoSeq/VoSeq#381]
```
[2018-02-01 10:19:45,075] [ERROR] [MainThread] [django.request] [124] Internal Server Error: /search/
Traceback (most recent call last):
  File "/home/voseq/.virtualenvs/voseq/lib/python3.4/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/voseq/.virtualenvs/voseq/lib/python3.4/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/voseq/.virtualenvs/voseq/lib/python3.4/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/voseq/.virtualenvs/voseq/lib/python3.4/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/voseq/VoSeq/voseq/public_interface/views.py", line 102, in search
    'voucher_code_list': get_voucher_code_list(sqs),
  File "/home/voseq/VoSeq/voseq/public_interface/utils.py", line 48, in get_voucher_code_list
    code = sqs[0].code
  File "/home/voseq/.virtualenvs/voseq/lib/python3.4/site-packages/django/db/models/query.py", line 295, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
```

**Comment by carlosp420** [comment]
This error is triggered when doing a simple search and searching for a voucher code that doses not exist in the database.
