### ISSUE TITLE
error when using make migrations after upgrading dependencies

### ISSUE THREAD

**Issue by mariespe** [VoSeq/VoSeq#385]
I'm using Mac OSX 10.11.6. 

Upgraded the dependencies as usual using:

    vagrant ssh
    cd /vagrant
    workon voseq
    pip install -r requirements/base.txt

Then I did 'git pull origin master' to update voseq.

When subsequently doing 'make migrations' I received the following error:
                                                                     
    (voseq) vagrant@vagrant-ubuntu-trusty-64:/vagrant$ make migrations 
    python voseq/manage.py makemigrations --settings=voseq.settings.local
    Traceback (most recent call last):
    File "voseq/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-   packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
    File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
    File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 1129, in _exec
    File "<frozen importlib._bootstrap>", line 1471, in exec_module
    File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
    File "/vagrant/voseq/public_interface/admin.py", line 18, in <module>
    from public_interface.views import change_selected
    File "/vagrant/voseq/public_interface/views.py", line 16, in <module>
    from core.utils import get_context
    File "/vagrant/voseq/core/utils.py", line 7, in <module>
    from typing import Dict, Any
    ImportError: No module named 'typing'
    make: *** [migrations] Error 1

I figured out that two of the requirements in the requirements/base.txt file were incompatible: django-haystack 2.5.0 needs django <1.10, but 1.10.4 is listed in the base file. So I upgraded haystack to 2.8.1, which again required updating django to 1.11.0 to make everything compatible. Tried 'make migrations' again, but now get the following error:

    (voseq) vagrant@vagrant-ubuntu-trusty-64:/vagrant$ make migrations
    python voseq/manage.py makemigrations --settings=voseq.settings.local
    Traceback (most recent call last):
    File "voseq/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-   packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
    File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
    File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 1129, in _exec
    File "<frozen importlib._bootstrap>", line 1471, in exec_module
    File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/easy_thumbnails/models.py", line 6, in <module>
      from easy_thumbnails import utils, signal_handlers
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/easy_thumbnails/utils.py", line 15, in <module>
      from easy_thumbnails.conf import settings
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/easy_thumbnails/conf.py", line 325, in <module>
      settings = Settings()
    File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/easy_thumbnails/conf.py", line 21, in __init__
      super(AppSettings, self).__init__(*args, **kwargs)
    TypeError: __init__() missing 1 required positional argument: 'settings_module'
    make: *** [migrations] Error 1

All other 'make' commands (e.g. make serve, make stats) also fail with the same error, and I get a '404 not found' when trying to access the database.
Also tried to downgrade Django to 1.9.3 and keep haystack 2.5.0, but then I still get the first error message above.

Finally, I tried exiting vagrant and logging back in, and restarted voseq, but the error persists. Also made sure that elasticsearch is running. 

Any idea how to fix this? I now can't access the database at all.

**Comment by carlosp420** [comment]
it needs the installation of the library `typing`
Latest commit to master 762f0ac fixes it.
