### ISSUE TITLE
error deploying docker image

### ISSUE THREAD

**Issue by cdoorenweerd** [VoSeq/VoSeq#434]
Hi Carlos, hope you are well! I'm trying to deploy a new docker image on a fresh ubuntu server but I'm getting this error that you can hopefully help with:

```terminal
Step 6/26 : RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list
 ---> Running in f03b9c93c8fc
Removing intermediate container f03b9c93c8fc
 ---> f04dab2edb90
Step 7/26 : RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main 12" | tee /etc/apt/sources.list.d/pgdg.list
 ---> Running in 96978eae758c
deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main 12
Removing intermediate container 96978eae758c
 ---> 88b5477e0f30
Step 8/26 : RUN curl -L https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
 ---> Running in 3c12acb02d59
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key output should not be parsed (stdout is not a terminal)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
gpg: no valid OpenPGP data found.
The command '/bin/sh -c curl -L https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -' returned a non-zero code: 2
ERROR: Service 'app' failed to build : Build failed
```

**Comment by hpwjnijs** [comment]
I suspect that _python:3.6-stretch_  is an outdated image, i.e. has outdated (root-)certificates. Either have a newer image, or 'fix'  curl with the -k option.

**Comment by mariespe** [comment]
I solved this error with adding the -k option for curl in the docker file as suggested above. After that I got another error telling me that postgresql-12 and postgresql-client-12 could not be found so I removed the version in the docker file and could proceed. Then, I however got the error below that I cannot solve, and would appreciate any help. I'm using a MacBook Pro with a M1 max chip running macOS Monterey.

```
[+] Running 4/4
 ⠿ Network voseq_default    C...                         0.0s
 ⠿ Volume "voseq_app_data"  Created                      0.0s
 ⠿ Volume "voseq_db_data"   Created                      0.0s
 ⠿ Container voseq_db_1     Cr...                        0.1s
[+] Running 1/1
 ⠿ Container voseq_db_1  Start...                        0.4s
wait_for_it.sh: waiting for db:5432 without a timeout
wait_for_it.sh: db:5432 is available after 1 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "insdb" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 87, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  database "insdb" does not exist
```

**Comment by carlosp420** [comment]
yeah, it looks like it is necessary to do upgrade many dependencies of libraries and docker images :-(

**Comment by carlosp420** [comment]
@mariespe make sure you are using the branch master when starting up VoSeq. The insdb database is for another branch (ins_db) that should not be used.

The error `django.db.utils.OperationalError: FATAL:  database "insdb" does not exist` means that there is a configuration setting that is expecting a postgres database called insdb, which is not present in your postgresql volume.

**Comment by mariespe** [comment]
Hi Carlos,

But how do I make sure that I use the master branch? I just followed the
voseq instructions when I got this error message.

Marianne

**Comment by carlosp420** [comment]
@mariespe fixed the insdb error. Just download the latest version v2.6.0 https://github.com/VoSeq/VoSeq/releases/tag/v2.6.0
and it should work out the box ( I upgraded the docker image) 

@cdoorenweerd I upgrade the docker image, download the latest version and follow the instructions to install using docker.
