### ISSUE TITLE
Migrate existing database in sql format

### ISSUE THREAD

**Issue by mariespe** [VoSeq/VoSeq#437]
Hi Carlos,

I now have Voseq up and running in Docker. How can I migrate and existing Voseq 2 database in sql format generated using pg_dump? I couldn't find any good answer online and can't generate an xml file since the computer where my old Voseq2 instance was running is dead...

**Comment by carlosp420** [comment]
from the Voseq2 you can dump your database using the command:
`pg_dump -d voseq > voseq.sql`

Then you copy the file to the computer of your new voseq and import the file.

You need to copy the file into the database container of your new voseq:
`docker cp voseq.sql voseq_db_1:/tmp/.`

Now, enter the database container:
`./run/scripts/docker_compose exec db bash`

You should see the file store in /tmp. Use this command ` ls -lrt /tmp/` inside the database container:
`root@ea1c2b05b196:/# ls -lrt /tmp/`

Create an empty database in postgres:

`su postgres`
`psql`
`create database voseq;`

Exit postgres with the command:  `\q`

Now import your backup database into the empty database of your new voseq (note you are still in the database container)

`psql -d voseq < /tmp/voseq.sql`

Exit the containers and rerun Voseq.

**Comment by mariespe** [comment]
Hi Carlos,

Thanks! This worked insofar that vouchers, genes and taxon sets were showing up in my new Voseq in Docker, but not the sequences. When running 
`psql -d voseq < /tmp/voseq.sql`
I did get an error saying that the code "gene" was not found, so I realised that in the old version in my sql file the code for genes was "gene_code" and in the new version it appears to be simply "gene", so I replaced this in the sql file, removed the newly created voseq database (using `drop database voseq` while in postgres) and did the process again to create a new one. This seemingly ran without errors, but now I get a server error 500 when I try to click anything both in the admin and web interfaces...

So I then removed the entire container and the Voseq folder downloaded from Github to be on the safe side, downloaded the most recent Voseq version again and attempted to make a new container. But when running 
`./run/scripts/docker_compose exec app bash`
I now get the below error, which indicates that this also has something to do with gene_code not existing, but being expected somewhere. Any help would be appreciated...

```
Running migrations:
  Applying public_interface.0002_auto_20201122_0756...Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column "gene_code" named in key does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.6/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 535, in alter_field
    old_db_params, new_db_params, strict)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/schema.py", line 124, in _alter_field
    new_db_params, strict,
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 715, in _alter_field
    self.execute(self._create_unique_sql(model, [new_field.column]))
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "gene_code" named in key does not exist

ERROR: 1

```

**Comment by carlosp420** [comment]
note to self:

alter table public_interface_genes rename COLUMN gene to gene_code;
alter table public_interface_sequences rename COLUMN gene to gene_code;

add back `gene_code = models.CharField(max_length=100, db_index=True)` to Sequences model.
up containers
